# Pair Programming EDA I

## Hipótesis
Las hipótesis que os planteamos para el conjunto de datos de historico_tickets_limpio_pandas son:

- Tiempo de resolución: 
    Se podría hipotetizar que los tickets con mayor severidad y prioridad son resueltos en menos días que los tickets con menor prioridad. Además, se podría examinar si hay alguna correlación entre el tipo de problema y el tiempo que toma resolverlo.
    
    La pregunta que contestaremos es: ¿Son los tickets con mayor severidad y prioridad los que se resuelven antes?

- Satisfacción del cliente: Se podría hipotetizar que la satisfacción del cliente está relacionada con la velocidad de resolución del ticket y la categoría del problema. Por ejemplo, los clientes podrían estar más satisfechos si sus problemas de acceso y login se resuelven rápidamente en comparación con los problemas de software más complejos.

    La pregunta que contestaremos es: ¿Están los clientes con problemas de acceso y login más contentos que los que tienen problemas de software?

    -   Desempeño del agente: Se podría hipotetizar que algunos agentes tienen un mejor desempeño que otros en la resolución de tickets. Se podrían explorar variables como el número de tickets asignados, el tiempo promedio de resolución y la satisfacción del cliente para identificar patrones en el desempeño de los agentes.

    La pregunta que contestaremos es: ¿Cuáles son los empleados que más tickets atienden? ¿Son los empleados que atienden más tickets los que tardan más en solucionar los problemas de los clientes? ¿Y la media de la satisfacción de los clientes es menor en aquellos empleados que atienden más solicitudes?

    - Cambios en el tiempo: Se podría hipotetizar que el volumen y la naturaleza de los problemas cambian con el tiempo. Por ejemplo, se podría explorar si hay un aumento en los problemas de acceso y login durante un determinado período de tiempo, o si hay una correlación entre la temporada del año y el tipo de problema reportado.

    La pregunta que contestaremos es: ¿Hay alguna diferencia entre a lo largo del tiempo entre las distintas categorías de solicitudes de tickets que tenemos?

## Objetivos
El objetivo principal de este pair es comprender la estructura de los datos, como es formato de los datos, el número de columnas y filas, el tipo de datos, la distribución de los datos, etc. Los objetivos específicos de hoy son:

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_tickets = pd.read_csv("datos/historico_tickets_limpio_pandas.csv", index_col= 0)

1. Haced una exploración inicial del dataframe:


- ¿Cuál es el número de filas y columnas? 


In [3]:
df_tickets.shape
print(f"En este dataframe hay {df_tickets.shape[1]} columnas y {df_tickets.shape[0]} filas")

En este dataframe hay 13 columnas y 97386 filas


- ¿Cuál es el porcentaje de valores nulos en cada columna? Presenta los resultados en un dataframe, donde las columnas sean el nombre de las variables y el porcentaje de nulos.


In [4]:
df_nulos = df_tickets.isnull().sum()*100/df_tickets.shape[0]
df_nulos.reset_index().T

0      1            2          3          4     5          6   \
index  id_ticket  fecha  id_empleado  id_agente  categoría  tipo  severidad   
0            0.0    0.0          0.0        0.0        0.0   0.0        0.0   

              7                8             9         10   11   12  
index  prioridad  días_resolución  satisfacción  semestre  año  mes  
0            0.0              0.0           0.0       0.0  0.0  0.0

- ¿Qué tipos de datos hay en cada columna?


In [5]:
df_tickets.dtypes

id_ticket          object
fecha              object
id_empleado         int64
id_agente           int64
categoría          object
tipo               object
severidad          object
prioridad          object
días_resolución     int64
satisfacción        int64
semestre           object
año                 int64
mes                object
dtype: object

- Extraed la información general del dataframe.

In [6]:
df_tickets.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 97386 entries, 0 to 29087
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   id_ticket        97386 non-null  object
 1   fecha            97386 non-null  object
 2   id_empleado      97386 non-null  int64 
 3   id_agente        97386 non-null  int64 
 4   categoría        97386 non-null  object
 5   tipo             97386 non-null  object
 6   severidad        97386 non-null  object
 7   prioridad        97386 non-null  object
 8   días_resolución  97386 non-null  int64 
 9   satisfacción     97386 non-null  int64 
 10  semestre         97386 non-null  object
 11  año              97386 non-null  int64 
 12  mes              97386 non-null  object
dtypes: int64(5), object(8)
memory usage: 10.4+ MB


2. Cread dos dataframes nuevos, uno que incluya solo las variables categóricas y otro que incluya solo las variables numéricas.

In [7]:
df_categorico = df_tickets.select_dtypes(include = "object")

In [8]:
df_numerico = df_tickets.select_dtypes(include = "int64")

- ¿Cuáles son los principales estádisticos de los dataframes?

In [9]:
df_categorico.describe(include = "object").T

count unique                top   freq
id_ticket  97386  97386  GDDENR-5042564453      1
fecha      97386   1827         2020-02-20    105
categoría  97386      4            Sistema  38961
tipo       97386      2          Solicitud  73138
severidad  97386      5         2 - Normal  88555
prioridad  97386      4           3 - Alta  35511
semestre   97386      2        2º semestre  49876
mes        97386     12            Octubre   8487

In [10]:
df_numerico.describe().T

count         mean         std     min     25%     50%  \
id_empleado      97386.0   999.160639  577.407222     1.0   500.0   999.0   
id_agente        97386.0    25.468856   14.449455     1.0    13.0    26.0   
días_resolución  97386.0     4.552749    4.365432     0.0     0.0     4.0   
satisfacción     97386.0     4.100990    1.257093     1.0     4.0     5.0   
año              97386.0  2018.399164    1.393095  2016.0  2017.0  2019.0   

                    75%     max  
id_empleado      1499.0  2000.0  
id_agente          38.0    50.0  
días_resolución     7.0    21.0  
satisfacción        5.0     5.0  
año              2020.0  2020.0

- Extraed los valores únicos.

In [13]:
for col in df_categorico.columns:
    print("------------------------------------------------------------", "\n")
    print(f"En la columna {col} tenemos los siguientes valores unicos")
    print(df_categorico[col].unique())
    print("\n", "------------------------------------------------------------", "\n")

------------------------------------------------------------ 

En la columna id_ticket tenemos los siguientes valores unicos
['GDDENR-5042564453' 'GDDENR-8042508060' 'GDDESR-1342539995' ...
 'TWRTSR-9643846768' 'TWRTSR-9944138906' 'TWRTST-8643986162']

 ------------------------------------------------------------ 

------------------------------------------------------------ 

En la columna fecha tenemos los siguientes valores unicos
['2016-07-13' '2016-05-18' '2016-06-18' ... '2020-06-03' '2020-06-12'
 '2020-02-19']

 ------------------------------------------------------------ 

------------------------------------------------------------ 

En la columna categoría tenemos los siguientes valores unicos
['Acceso/Login' 'Sistema' 'Software' 'Hardware']

 ------------------------------------------------------------ 

------------------------------------------------------------ 

En la columna tipo tenemos los siguientes valores unicos
['Problema' 'Solicitud']

 --------------------------

In [14]:
for col in df_numerico.columns:
    print("------------------------------------------------------------", "\n")
    print(f"En la columna {col} tenemos los siguientes valores unicos")
    print(df_numerico[col].unique())
    print("\n", "------------------------------------------------------------", "\n")

------------------------------------------------------------ 

En la columna id_empleado tenemos los siguientes valores unicos
[1735 1566  569 ... 1528 1367 1600]

 ------------------------------------------------------------ 

------------------------------------------------------------ 

En la columna id_agente tenemos los siguientes valores unicos
[ 4 10 29 40 31 20 36 18 12 42  5 21 17  2 24 23 15 46 43 27  8 45 32 38
 33 41  3  9 25 39 16 47 14 48 37 35 34 28 30  1 11 19 44  6 26 49  7 22
 50 13]

 ------------------------------------------------------------ 

------------------------------------------------------------ 

En la columna días_resolución tenemos los siguientes valores unicos
[ 0  3  9  1  2  5  8  4 10  6  7 13 16 17 11 12 14 15 19 18 21 20]

 ------------------------------------------------------------ 

------------------------------------------------------------ 

En la columna satisfacción tenemos los siguientes valores unicos
[5 1 4 3 2]

 ----------------------

BONUS presenta los resultados en un dataframe. Os deberá quedar algo como esto:

Donde variable es cada una de las variables categóricas que tenemos en el dataset y n_unicos es una lista con los nombres de los valores únicos de cada variable.

In [22]:
dic_columnas = {"variables":[], "unicos":[]}

for col in df_categorico.columns:
    dic_columnas["variables"].append(col)
    dic_columnas["unicos"].append(df_categorico[col].unique())

df_cat_unicos = pd.DataFrame(dic_columnas)
df_cat_unicos

variables                                             unicos
0  id_ticket  [GDDENR-5042564453, GDDENR-8042508060, GDDESR-...
1      fecha  [2016-07-13, 2016-05-18, 2016-06-18, 2016-04-2...
2  categoría        [Acceso/Login, Sistema, Software, Hardware]
3       tipo                              [Problema, Solicitud]
4  severidad  [0 - Sin Clasificar, 2 - Normal, 4 - Crítico, ...
5  prioridad   [0 - Sin Asignar, 3 - Alta, 2 - Media, 1 - Baja]
6   semestre                          [2º semestre, 1 semestre]
7        mes  [Julio, Mayo, Junio, Abril, Agosto, Marzo, Ene...

## Conclusiones
De qué nos sirven estos números y dataframe? Extraed conclusiones de ellos.
Por ejemplo:


¿Hay alguna columna que no tenga sentido su tipo de datos?

- No, ya que eliminamos la columna llamada Unamed: 0.

¿Hay alguna columna que no tenga sentido su nombre?


- No, ya que eliminamos la columna llamada Unamed: 0

¿Hay alguna columna que no tenga sentido su contenido?


- No, ya que eliminamos la columna llamada Unamed: 0

¿Hay alguna columna que tenga demasiadas categorías o valores que nos pueda hacer difícil trabajar con ella?

- En este analisis exploratorio de datos no encontramos ninguna columna con la que fuera tedioso trabajar. 